### ISSUE TITLE
Automate adding and removing "For Milestone Bug"

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-repos-automation#10]
https://github.com/microsoft/TypeScript/labels/For%20Milestone%20Bug

**Comment by orta** [comment]
This could propagate to PRs easily too

**Comment by sandersn** [comment]
There are 3 labels tracking only PRs on the Typescript repo:

* For Milestone Bug -- fixes an issue that's in a version milestone, or assigned to a team member
* For Backlog Bug -- fixes an issue that's in the Backlog milestone.
* For Uncommitted Bug -- any other PR.

These need to update as their linked issues update.

You could confidently add the Housekeeping label to any PR that only touches files in, say, scripts/ or perhaps src/harness (except unit tests, I think they're in there somewhere). That will miss many categories of Housekeeping PRs, like type-annotation-only ones, but there aren't many of them anyway.
